# Ayu Mirage (dark) — kitty colors
background              #1f2430
foreground             #cccac2
cursor                 #ffcc66
cursor_text_color      #1f2430

selection_background   #33415e
selection_foreground   #cccac2

url_color              #73d0ff

# black
color0  #191e2a
color8  #686868
# red
color1  #f28779
color9  #f28779
# green
color2  #87d96c
color10 #d5ff80
# yellow
color3  #ffd173
color11 #ffcc66
# blue
color4  #6dcbfa
color12 #73d0ff
# magenta
color5  #dfbfff
color13 #dfbfff
# cyan
color6  #90e1c6
color14 #95e6cb
# white
color7  #c7c7c7
color15 #ffffff
